version: '3.8'

services:
  # Database service
  postgres:
    image: postgres:15-alpine
    container_name: talk_metrics_db
    environment:
      POSTGRES_DB: talk_metrics
      POSTGRES_USER: talk_metrics_user
      POSTGRES_PASSWORD: talk_metrics_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - talk_metrics_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U talk_metrics_user -d talk_metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: talk_metrics_backend
    ports:
      - "4001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: talk_metrics
      DB_USER: talk_metrics_user
      DB_PASSWORD: talk_metrics_password
      DB_SSL: false
      OPENAI_API_KEY: ${OPENAI_API_KEY:-your_openai_api_key_here}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4}
      WHATSAPP_API_URL: ${WHATSAPP_API_URL:-https://api.wazzup24.com}
      WHATSAPP_API_TOKEN: ${WHATSAPP_API_TOKEN:-your_whatsapp_api_token_here}
      UPLOAD_MAX_SIZE: 10485760
      UPLOAD_ALLOWED_TYPES: txt,json
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      CORS_ORIGIN: http://localhost:4000
      LOG_LEVEL: info
      LOG_FILE_PATH: ./logs/app.log
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_here_change_in_production}
      SESSION_SECRET: ${SESSION_SECRET:-your_session_secret_here_change_in_production}
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
    networks:
      - talk_metrics_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: talk_metrics_frontend
    ports:
      - "4000:80"
    networks:
      - talk_metrics_network
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  talk_metrics_network:
    driver: bridge